/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.aurura.openwordjava;

/**
 *
 * @author jiangyue
 */
public class WordDashboard extends javax.swing.JFrame {

    private WordMgr dataSide;
    
    /**
     * Creates new form WordDashbord
     * @param mgr
     */
    public WordDashboard(WordMgr mgr) {
        this.dataSide = mgr;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        AddButt = new javax.swing.JButton();
        WordOri = new javax.swing.JTextField();
        WordDef = new javax.swing.JTextField();
        WordNot = new javax.swing.JTextField();
        LabelOri = new javax.swing.JLabel();
        LabelDef = new javax.swing.JLabel();
        LabelNot = new javax.swing.JLabel();
        LoadButt = new javax.swing.JButton();
        Recite = new javax.swing.JPanel();
        startSession = new javax.swing.JButton();
        uselessLabel5 = new javax.swing.JLabel();
        sessionCheck = new javax.swing.JButton();
        defineField = new javax.swing.JTextField();
        uselessLabel2 = new javax.swing.JLabel();
        uselessLabel1 = new javax.swing.JLabel();
        uselessLabel3 = new javax.swing.JLabel();
        uselessLabel4 = new javax.swing.JLabel();
        txtLabel = new javax.swing.JLabel();
        defLabel = new javax.swing.JLabel();
        notLabel = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        workingFileSelect = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        workingFileLabel = new javax.swing.JLabel();
        changeFileEvent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        Dashboard.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DashboardFocusGained(evt);
            }
        });

        AddButt.setText("Add word");
        AddButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtActionPerformed(evt);
            }
        });

        LabelOri.setText("Word");

        LabelDef.setText("Defination");

        LabelNot.setText("Notation");

        LoadButt.setText("Load");
        LoadButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(WordNot, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNot))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(AddButt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LoadButt))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(WordOri, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelOri))
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addComponent(WordDef, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelDef)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButt)
                    .addComponent(LoadButt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WordOri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelOri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WordDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelDef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WordNot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNot))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard", Dashboard);

        startSession.setText("Get a word");
        startSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSessionActionPerformed(evt);
            }
        });

        uselessLabel5.setText("Status:");

        sessionCheck.setText("Check!");
        sessionCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionCheckActionPerformed(evt);
            }
        });

        uselessLabel2.setText("Word is..");

        uselessLabel1.setText("Word Text:");

        uselessLabel3.setText("Defination:");

        uselessLabel4.setText("Notation:");

        txtLabel.setText("..");

        defLabel.setText("..");

        notLabel.setText("..");

        statLabel.setText("..");

        javax.swing.GroupLayout ReciteLayout = new javax.swing.GroupLayout(Recite);
        Recite.setLayout(ReciteLayout);
        ReciteLayout.setHorizontalGroup(
            ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReciteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uselessLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ReciteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReciteLayout.createSequentialGroup()
                        .addComponent(uselessLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(defineField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sessionCheck))
                    .addGroup(ReciteLayout.createSequentialGroup()
                        .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ReciteLayout.createSequentialGroup()
                                .addComponent(uselessLabel3)
                                .addGap(25, 25, 25)
                                .addComponent(defLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ReciteLayout.createSequentialGroup()
                                .addComponent(uselessLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(notLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ReciteLayout.createSequentialGroup()
                                .addComponent(uselessLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ReciteLayout.setVerticalGroup(
            ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReciteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSession)
                    .addComponent(uselessLabel5)
                    .addComponent(statLabel))
                .addGap(18, 18, 18)
                .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sessionCheck)
                    .addComponent(uselessLabel2))
                .addGap(18, 18, 18)
                .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uselessLabel1)
                    .addComponent(txtLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uselessLabel3)
                    .addComponent(defLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReciteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uselessLabel4)
                    .addComponent(notLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recite", Recite);

        workingFileSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingFileSelectActionPerformed(evt);
            }
        });

        jLabel1.setText("Your currently working file:");

        workingFileLabel.setText("..");

        changeFileEvent.setText("Change");
        changeFileEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFileEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(workingFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(workingFileSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeFileEvent)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(workingFileLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workingFileSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeFileEvent))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Working File", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtActionPerformed
        dataSide.addWord(WordOri.getText(), WordDef.getText(), WordNot.getText());
        WordOri.setText("");
        WordDef.setText("");
        WordNot.setText("");
    }//GEN-LAST:event_AddButtActionPerformed

    private void startSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSessionActionPerformed
        /* If yes session. */
        if(dataSide.isSessionExist()) {
            dataSide.killSession(); 
            startSession.setText("Get a word");
            statLabel.setText("..");
            txtLabel.setText("..");
            notLabel.setText("..");
            defLabel.setText("..");
            defineField.setText("");
            return;
        }
        /* If no session.. */
        String str = dataSide.startWordSession();
        // Now display it
        statLabel.setText("Testing..");
        defLabel.setText(str);
    }//GEN-LAST:event_startSessionActionPerformed

    private void sessionCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionCheckActionPerformed
        boolean bool = dataSide.wordSessionCheck(defineField.getText());
        Word wd = dataSide.getSessionWord();
        // Display the stubborn stuff.
        statLabel.setText("Result: " + bool + " Streak: " + wd.getStreak());
        txtLabel.setText(wd.getText());
        notLabel.setText(wd.getNote());
        startSession.setText("I'm done!");
        
        
    }//GEN-LAST:event_sessionCheckActionPerformed

    private void LoadButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtActionPerformed
        dataSide.loadOnDisk();
    }//GEN-LAST:event_LoadButtActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        workingFileLabel.setText(dataSide.getWorkingFile());
        workingFileSelect.setText(dataSide.getWorkingFile());
        LoadButt.setText("Load from " + dataSide.getWorkingFile());
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void workingFileSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingFileSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workingFileSelectActionPerformed

    private void changeFileEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFileEventActionPerformed
        dataSide.changeWorkingFile(workingFileSelect.getText());
    }//GEN-LAST:event_changeFileEventActionPerformed

    private void DashboardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DashboardFocusGained
        LoadButt.setText("Load from " + dataSide.getWorkingFile());
    }//GEN-LAST:event_DashboardFocusGained

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButt;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JLabel LabelDef;
    private javax.swing.JLabel LabelNot;
    private javax.swing.JLabel LabelOri;
    private javax.swing.JButton LoadButt;
    private javax.swing.JPanel Recite;
    private javax.swing.JTextField WordDef;
    private javax.swing.JTextField WordNot;
    private javax.swing.JTextField WordOri;
    private javax.swing.JButton changeFileEvent;
    private javax.swing.JLabel defLabel;
    private javax.swing.JTextField defineField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel notLabel;
    private javax.swing.JButton sessionCheck;
    private javax.swing.JButton startSession;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel txtLabel;
    private javax.swing.JLabel uselessLabel1;
    private javax.swing.JLabel uselessLabel2;
    private javax.swing.JLabel uselessLabel3;
    private javax.swing.JLabel uselessLabel4;
    private javax.swing.JLabel uselessLabel5;
    private javax.swing.JLabel workingFileLabel;
    private javax.swing.JTextField workingFileSelect;
    // End of variables declaration//GEN-END:variables
}
